### ISSUE TITLE
It should be possible to redirect to another redirect

### ISSUE THREAD

**Issue by Fastjur** [WISVCH/mand#34]
It should be possible to redirect from one link to another redirect within mand.

Per example, one should be able to link wisv.ch/parentsday to wisv.ch/ouderdag and ouderdag links to it's url, making both links valid, without having to edit it in multiple spots.

**Comment by martijnjanssen** [comment]
I'm closing this as discussed, redirecting to another link is fast enough. So that'll be the solution for this.
